export const LOADING = "LOADING";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_ERROR = "LOADING_ERROR";

export const PLANETS_FETCHED = "PLANETS_FETCHED";
export const PLANET_FETCHING_ERROR = "PLANET_FETCHING_ERROR";
